// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	d2d: KVNamespace;
	NEXTJS_ENV: string;
	D1_DB: D1Database;
	WORKER_ASSETS: Fetcher;
}
