name: "NextJsExpressApp"
services:
  nextjs_express_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18.19.0 # Only used for selecting Node.js version at build time
    environment:
      NODE_ENV: production
      SERVER_URL: ${SERVER_URL}
      PORT: ${PORT}
      USE_REDIS: ${USE_REDIS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASS: ${REDIS_PASS}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: ${REDIS_URL}
      COOKIE_SECRET: ${COOKIE_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5438:5438"
